### ISSUE TITLE
[stderr] [error] Couldn't create process: 2

### ISSUE THREAD

**Issue by UnclWish** [AltimorTASDK/dsr-shader-mods#2]
I get this error on cracked steam version of the game.
Can you help with that?

**Comment by UnclWish** [comment]
This is ModEngine2 issue. It can be used dsr-lighting through injecting dll via other tool.

**Comment by AltimorTASDK** [comment]
Neither I nor the original ModEngine2 team offer support for cracked versions. Please support FromSoftware.
